In [73]:
%config IPCompleter.greedy=True

In [72]:
import numpy as np

Array gen

In [3]:

List=[1,2,3,4,]
a=np.array(List)
print(a)

[1 2 3 4]


In [4]:

a.reshape(2,2)# note #*# must equal len(array)


array([[1, 2],
       [3, 4]])

In [14]:

a=np.arange(250)
print(a)



[  0   1   2   3   4   5   6   7   8   9  10  11  12  13  14  15  16  17
  18  19  20  21  22  23  24  25  26  27  28  29  30  31  32  33  34  35
  36  37  38  39  40  41  42  43  44  45  46  47  48  49  50  51  52  53
  54  55  56  57  58  59  60  61  62  63  64  65  66  67  68  69  70  71
  72  73  74  75  76  77  78  79  80  81  82  83  84  85  86  87  88  89
  90  91  92  93  94  95  96  97  98  99 100 101 102 103 104 105 106 107
 108 109 110 111 112 113 114 115 116 117 118 119 120 121 122 123 124 125
 126 127 128 129 130 131 132 133 134 135 136 137 138 139 140 141 142 143
 144 145 146 147 148 149 150 151 152 153 154 155 156 157 158 159 160 161
 162 163 164 165 166 167 168 169 170 171 172 173 174 175 176 177 178 179
 180 181 182 183 184 185 186 187 188 189 190 191 192 193 194 195 196 197
 198 199 200 201 202 203 204 205 206 207 208 209 210 211 212 213 214 215
 216 217 218 219 220 221 222 223 224 225 226 227 228 229 230 231 232 233
 234 235 236 237 238 239 240 241 242 243 244 245 24

In [15]:

print(a.reshape(5,5,10))


[[[  0   1   2   3   4   5   6   7   8   9]
  [ 10  11  12  13  14  15  16  17  18  19]
  [ 20  21  22  23  24  25  26  27  28  29]
  [ 30  31  32  33  34  35  36  37  38  39]
  [ 40  41  42  43  44  45  46  47  48  49]]

 [[ 50  51  52  53  54  55  56  57  58  59]
  [ 60  61  62  63  64  65  66  67  68  69]
  [ 70  71  72  73  74  75  76  77  78  79]
  [ 80  81  82  83  84  85  86  87  88  89]
  [ 90  91  92  93  94  95  96  97  98  99]]

 [[100 101 102 103 104 105 106 107 108 109]
  [110 111 112 113 114 115 116 117 118 119]
  [120 121 122 123 124 125 126 127 128 129]
  [130 131 132 133 134 135 136 137 138 139]
  [140 141 142 143 144 145 146 147 148 149]]

 [[150 151 152 153 154 155 156 157 158 159]
  [160 161 162 163 164 165 166 167 168 169]
  [170 171 172 173 174 175 176 177 178 179]
  [180 181 182 183 184 185 186 187 188 189]
  [190 191 192 193 194 195 196 197 198 199]]

 [[200 201 202 203 204 205 206 207 208 209]
  [210 211 212 213 214 215 216 217 218 219]
  [220 221 222 223 224 2

In [16]:

print(np.zeros(10,dtype=np.int))

[0 0 0 0 0 0 0 0 0 0]


In [6]:

x=np.linspace(10,20,5,endpoint=False)# include endpoint or not
print(x)


[10. 12. 14. 16. 18.]


In [8]:
x=np.logspace(1.0,2.0, num=50,base=10.0)
print(x)


[ 10.          10.48113134  10.98541142  11.51395399  12.06792641
  12.64855217  13.25711366  13.89495494  14.56348478  15.26417967
  15.9985872   16.76832937  17.57510625  18.42069969  19.30697729
  20.23589648  21.20950888  22.22996483  23.29951811  24.42053095
  25.59547923  26.82695795  28.11768698  29.47051703  30.88843596
  32.37457543  33.93221772  35.56480306  37.2759372   39.06939937
  40.94915062  42.9193426   44.98432669  47.14866363  49.41713361
  51.79474679  54.28675439  56.89866029  59.63623317  62.50551925
  65.51285569  68.6648845   71.9685673   75.43120063  79.06043211
  82.86427729  86.85113738  91.0298178   95.40954763 100.        ]


In [9]:
#indexing and spiceing

a=np.arange(10)
print(a)
s=slice(2,7,2)

print(a[s])
print(a[2:7:2])
print(a[2::3])


[0 1 2 3 4 5 6 7 8 9]
[2 4 6]
[2 4 6]
[2 5 8]


In [24]:

tt=np.array([1,2,3,4])
pp=np.array([10,20,30,40])

print (tt*pp)
print (tt*5)
print([1,2,3,4]*2, [1,2,3,4]+[5])

[ 10  40  90 160]
[ 5 10 15 20]
[1, 2, 3, 4, 1, 2, 3, 4] [1, 2, 3, 4, 5]


numpy does element wise operations vs a python list that just duplicates. therefore you can add, square root... but you have to use the np equivlent 

In [10]:

a= np.arange(9).reshape(3,3)
b=np.arange(3)
print(a+b)


[[ 0  2  4]
 [ 3  5  7]
 [ 6  8 10]]


In [71]:
randdd=np.random.randint(1, high=10, size=50, dtype=np.int).reshape(2,5,5)
print(randdd)

r= np.random.random((10,10))
print(r)

gaussinen_diss = np.random.randn(10,10)
print(gaussinen_diss)

[[[6 6 6 8 4]
  [9 5 1 6 8]
  [6 8 3 1 1]
  [6 7 1 7 2]
  [5 2 5 3 1]]

 [[6 6 2 2 4]
  [9 3 6 7 4]
  [7 9 1 8 6]
  [6 7 8 5 8]
  [2 8 8 6 7]]]
[[0.30736518 0.49420302 0.41846386 0.74777747 0.62899753 0.8402317
  0.92794003 0.97609448 0.89437185 0.12272922]
 [0.85278487 0.9273299  0.67601655 0.35376051 0.17833769 0.33116591
  0.11146638 0.69114107 0.39730606 0.87135525]
 [0.96226047 0.27804647 0.84119257 0.55566461 0.80789584 0.85192167
  0.66038181 0.58910861 0.34217128 0.73782117]
 [0.01769422 0.74709074 0.17327865 0.56710241 0.3137112  0.92567226
  0.551208   0.72908339 0.8969986  0.35931462]
 [0.45216417 0.40762156 0.69510455 0.02923619 0.96140432 0.64380303
  0.76247771 0.46064341 0.13602602 0.5031018 ]
 [0.07194317 0.86306312 0.96842167 0.78176718 0.6458644  0.62193746
  0.24954313 0.97235522 0.4883044  0.12706028]
 [0.24104183 0.56150486 0.74373121 0.82471462 0.5073391  0.38715685
  0.18909669 0.04549159 0.65518022 0.81092934]
 [0.84598834 0.90914765 0.05502278 0.82803583 0.0088

In [70]:
for i,k in enumerate(np.nditer(randdd)):
    if i ==6:
        break
    print(k)

5
5
3
9
1
6


In [44]:
 a= np.array([1,2])
 b = np.array([2,1])
 

dot product . and *

In [29]:
# python

dot = sum(i*j for i,j in zip(a,b))
print(dot)

4


In [90]:
# numpy 
c =(a*b)
print(c)
print(sum(c),np.sum(c),(c).sum(),np.dot(a,b),a.dot(b))

[2 2]
4 4 4 4 4


In [95]:
print(a@b,a*b)

4 [2 2]


magnitude and angles

In [50]:

print(np.sqrt((a*a).sum()),
     np.linalg.norm(a))



2.23606797749979 2.23606797749979


In [53]:
cos = a.dot(b) / (np.linalg.norm(a)*np.linalg.norm(b))
print(cos)

0.7999999999999998


In [55]:
angle = np.arccos(cos)
print(angle)

0.6435011087932847


vector and matrices

In [65]:
L = [[1,2],[3,4]]
M =  np.array(L)
Mat = np.matrix(L)
npM = np.array(Mat)

In [64]:
print(
L[0][0],
M[0,0],
M[0][0],
Mat[0,0],
Mat[0][0])

1 1 1 1 [[1 2]]


In [75]:
print(npM.T,"\n\n",Mat.T)

[[1 3]
 [2 4]] 

 [[1 3]
 [2 4]]


In [83]:
#inverse and ident , determence 
mInv= np.linalg.inv(M)
mdeter =  np.linalg.det(M)
print(aInv,mInv.dot(M),mdeter, )

[[-2.   1. ]
 [ 1.5 -0.5]]

[[1.00000000e+00 0.00000000e+00]
 [1.11022302e-16 1.00000000e+00]]

-2.0000000000000004


In [88]:
# diangnel and traspose

print(np.diag(M),M.T,sep="\n\n")

[1 4]

[[1 3]
 [2 4]]


In [103]:
diagArray =  np.diag( [1,2,3,4,5,6])

print (diagArray)
print(diagArray.sum(), diagArray.trace(), np.trace(diagArray))

[[1 0 0 0 0 0]
 [0 2 0 0 0 0]
 [0 0 3 0 0 0]
 [0 0 0 4 0 0]
 [0 0 0 0 5 0]
 [0 0 0 0 0 6]]
21 21 21


In [99]:
#outer product and inner


print(np.outer(a,b))
print(np.inner(a,b))


[[2 1]
 [4 2]]
4


Statistics

In [74]:
print(gaussinen_diss.mean())
print(gaussinen_diss.var())

-0.0693864547052572
1.012873130631609


Eigen 

In [108]:
#  init 
X = np.random.randn(100,3)

coVar = np.cov(X)
coVar.shape
covVarReal = np.cov(X.T)

print(x,coVar,coVar.shape,covVarReal,covVarReal.shape,sep="\n\n\n")

[ 10.          10.48113134  10.98541142  11.51395399  12.06792641
  12.64855217  13.25711366  13.89495494  14.56348478  15.26417967
  15.9985872   16.76832937  17.57510625  18.42069969  19.30697729
  20.23589648  21.20950888  22.22996483  23.29951811  24.42053095
  25.59547923  26.82695795  28.11768698  29.47051703  30.88843596
  32.37457543  33.93221772  35.56480306  37.2759372   39.06939937
  40.94915062  42.9193426   44.98432669  47.14866363  49.41713361
  51.79474679  54.28675439  56.89866029  59.63623317  62.50551925
  65.51285569  68.6648845   71.9685673   75.43120063  79.06043211
  82.86427729  86.85113738  91.0298178   95.40954763 100.        ]


[[ 2.05779243e+00  6.81835559e-02  5.19019239e-01 ... -1.01762708e-01
   3.43642452e-01  2.70771908e-01]
 [ 6.81835559e-02  2.50566927e-03  2.25647675e-02 ...  9.36839631e-03
  -4.71313070e-03  1.10705803e-03]
 [ 5.19019239e-01  2.25647675e-02  2.47802729e-01 ...  2.51798099e-01
  -2.63950835e-01 -1.02989772e-01]
 ...
 [-1.01762708e-01

In [110]:
# eigen
eigh = np.linalg.eigh(covVarReal)

eig = np.linalg.eig(covVarReal)
# the first row is eigen values and next one is eigen matrix
print(eigh,eig,sep="\n")

(array([0.7670665 , 1.01334844, 1.07356269]), array([[ 0.8254836 ,  0.28635179, -0.48639436],
       [ 0.30831089, -0.95058957, -0.03638497],
       [-0.47278031, -0.11992548, -0.87298148]]))
(array([0.7670665 , 1.07356269, 1.01334844]), array([[ 0.8254836 ,  0.48639436, -0.28635179],
       [ 0.30831089,  0.03638497,  0.95058957],
       [-0.47278031,  0.87298148,  0.11992548]]))


Linear Systems

In [117]:
solu =  np.linalg.inv(M).dot(b)

print(solu,np.linalg.solve(M,b))

[-3.   2.5] [-3.   2.5]


<h1>Linear System example</h1>
In the past, I would have set this up by picking a variable for one of the groups (say, "O" for "children") and then use "(total) less (what I've already accounted for)" (in this case, "2200 – O") for the other group. Using a system of equations, however, allows me to use two different variables for the two different unknowns.

number of adults: K

number of children: O

With these variables, I can create equations for the totals they've given me:

total number: K + O = 2200

total income: 4K + 1.5O = 5050

In [121]:
m1 =  np.array([[1,1],[4,1.5]])
m2 =  np.array([2200,5050])
k,o =  np.linalg.solve(m1,m2)
print(k,o,np.linalg.solve(m1,m2))

700.0 1500.0 [ 700. 1500.]
