In [1]:
from pandas import DataFrame
from pandas import Series
import numpy as np

<h1>Loading Data</h1>

In [2]:
import pandas as pd

path=""
# skip that last 0 rows does not work with the default engine
dataCSV= pd.read_csv("data_2d.csv",header=None,engine ="python",skipfooter =0)
print(dataCSV.info())

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
0    100 non-null float64
1    100 non-null float64
2    100 non-null float64
dtypes: float64(3)
memory usage: 2.4 KB
None


In [3]:
dataJSON= pd.read_json("CssOutput.json")
print(dataJSON.info())
print(dataJSON.head(5))

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 100 entries, 0 to 99
Data columns (total 3 columns):
Author    100 non-null object
Quote     100 non-null object
Tags      100 non-null object
dtypes: object(3)
memory usage: 2.4+ KB
None
              Author                                              Quote  \
0  [ALBERT EINSTEIN]  [The world as we have created it is a process ...   
1     [J.K. ROWLING]  [It is our choices, Harry, that show what we t...   
2  [ALBERT EINSTEIN]  [There are only two ways to live your life. On...   
3      [JANE AUSTEN]  [The person, be it gentleman or lady, who has ...   
4   [MARILYN MONROE]  [Imperfection is beauty, madness is genius and...   

                                         Tags  
0       [change,deep-thoughts,thinking,world]  
1                         [abilities,choices]  
2  [inspirational,life,live,miracle,miracles]  
3             [aliteracy,books,classic,humor]  
4                 [be-yourself,inspirational]  


In [4]:
# choseing your index
temp = dataJSON.head(10)
temp = temp.set_index('Author')
print(temp)

                                                                 Quote  \
Author                                                                   
[ALBERT EINSTEIN]    [The world as we have created it is a process ...   
[J.K. ROWLING]       [It is our choices, Harry, that show what we t...   
[ALBERT EINSTEIN]    [There are only two ways to live your life. On...   
[JANE AUSTEN]        [The person, be it gentleman or lady, who has ...   
[MARILYN MONROE]     [Imperfection is beauty, madness is genius and...   
[ALBERT EINSTEIN]    [Try not to become a man of success. Rather be...   
[ANDRÉ GIDE]         [It is better to be hated for what you are tha...   
[THOMAS A. EDISON]   [I have not failed. I've just found 10,000 way...   
[ELEANOR ROOSEVELT]  [A woman is like a tea bag; you never know how...   
[STEVE MARTIN]       [A day without sunshine is like, you know, nig...   

                                                           Tags  
Author                                       

In [5]:
# dataEXCEL= pd.read_excel(path)

<h1>DataFrame</h1>

In [6]:
spacer='\n'+'='*125+"\n\n\n\n\n"

data={"Name":["Rob","Bucky","Onizuka"]
,"Age":[34,28,23]
,"Salary":[1000,5000,2]}

data=DataFrame(data)
print(data)


   Age     Name  Salary
0   34      Rob    1000
1   28    Bucky    5000
2   23  Onizuka       2


In [7]:
# data


New_frame=DataFrame(data=data, columns=["Salary","Name","Age"])
print(spacer,New_frame)
New_frame=DataFrame(data=data, columns=["Salary","Name","Nationailty","Age"])
print(spacer,New_frame)







    Salary     Name  Age
0    1000      Rob   34
1    5000    Bucky   28
2       2  Onizuka   23





    Salary     Name  Nationailty  Age
0    1000      Rob          NaN   34
1    5000    Bucky          NaN   28
2       2  Onizuka          NaN   23


<h2>Columns title</h2>

In [8]:
print(dataJSON.columns.values)
dataJSON.columns = ['BY', 'Quote', 'About']
print(dataJSON.columns.values)


['Author' 'Quote' 'Tags']
['BY' 'Quote' 'About']


In [9]:
# acess and splicing and splitting
############################################
# row or ix[] iloc []
print(spacer,New_frame["Salary"])
print(spacer,New_frame.iloc[2])# ix is refering to x axis

#  getting the first row
# print(dataCSV.ix[0]) # derepc
print(dataCSV.iloc[0])

#  getting data form all the rows where 1st value is less that 5
print(dataCSV[dataCSV[0]<5])
# 






 0    1000
1    5000
2       2
Name: Salary, dtype: int64





 Salary               2
Name           Onizuka
Nationailty        NaN
Age                 23
Name: 2, dtype: object
0     17.930201
1     94.520592
2    320.259530
Name: 0, dtype: float64
           0          1           2
5   3.192702  29.256299   94.618811
44  3.593966  96.252217  293.237183
54  4.593463  46.335932  145.818745
90  1.382983  84.944087  252.905653
99  4.142669  52.254726  168.034401


In [10]:
print(dataJSON.loc[0])
#  getting certain index / rows/ colunms
tempJson = pd.read_json("supermarkets.json")
print(tempJson.head(),"\n\n\n\n\n\n")
tempJson = tempJson.set_index("Address")
# selection by label.
print(tempJson.loc['735 Dolores St':'332 Hill St','Country':'ID'],tempJson.loc[:,'Country':'ID'],tempJson.loc[:,'Country'],sep=spacer)
# location based indexing for selection by position.
print('='*125,"\n",tempJson.iloc[0:3,1:3])
print('\n\n',tempJson.ix[3,'Name'])

BY                                       [ALBERT EINSTEIN]
Quote    [The world as we have created it is a process ...
About                [change,deep-thoughts,thinking,world]
Name: 0, dtype: object
           Address           City Country  Employees  ID         Name  \
0     3666 21st St  San Francisco     USA          8   1      Madeira   
1   735 Dolores St  San Francisco     USA         15   2  Bready Shop   
2      332 Hill St  San Francisco     USA         25   3  Super River   
3     3995 23rd St  San Francisco     USA         10   4   Ben's Shop   
4  1056 Sanchez St  San Francisco     USA         12   5      Sanchez   

              State  
0          CA 94114  
1          CA 94119  
2  California 94114  
3          CA 94114  
4        California   






               Country  Employees  ID
Address                              
735 Dolores St     USA         15   2
332 Hill St        USA         25   3




                Country  Employees  ID
Address                    

C:\ProgramData\Anaconda3\lib\site-packages\ipykernel_launcher.py:10: DeprecationWarning: 
.ix is deprecated. Please use
.loc for label based indexing or
.iloc for positional indexing

See the documentation here:
http://pandas.pydata.org/pandas-docs/stable/indexing.html#ix-indexer-is-deprecated
  # Remove the CWD from sys.path while we load stuff.


In [11]:
print(New_frame)

New_frame["EDU.LVL."]="MS"
print(New_frame,"",sep=spacer)
### Transposing
New_frame=New_frame.T
print(New_frame,"",sep=spacer)

New_frame=New_frame.T
# New_frame.reindex([0,2,1])
#
# fields=["Alpha","Beta","Gamma"]
#
# New_frame=New_frame.reindex(columns=fields)
# drops a row
print(New_frame,"",sep=spacer)

New_frame=New_frame.drop([2,0])# a list



   Salary     Name  Nationailty  Age
0    1000      Rob          NaN   34
1    5000    Bucky          NaN   28
2       2  Onizuka          NaN   23
   Salary     Name  Nationailty  Age EDU.LVL.
0    1000      Rob          NaN   34       MS
1    5000    Bucky          NaN   28       MS
2       2  Onizuka          NaN   23       MS





                0      1        2
Salary       1000   5000        2
Name          Rob  Bucky  Onizuka
Nationailty   NaN    NaN      NaN
Age            34     28       23
EDU.LVL.       MS     MS       MS





  Salary     Name Nationailty Age EDU.LVL.
0   1000      Rob         NaN  34       MS
1   5000    Bucky         NaN  28       MS
2      2  Onizuka         NaN  23       MS







In [ ]:
# for droping  a col

New_frame=New_frame.drop("Nationailty",axis=1)
print(New_frame)

In [41]:
print(
    tempJson,tempJson.drop('332 Hill St'),
    tempJson.drop('332 Hill St',0),
    tempJson.drop(tempJson.index[0:3]),
    tempJson.drop(tempJson.index[0:3],0),    
    tempJson.drop(tempJson.columns[0:3],1),

    
    sep=spacer)


                          City Country  Employees  ID         Name  \
Address                                                              
3666 21st St     San Francisco     USA          8   1      Madeira   
735 Dolores St   San Francisco     USA         15   2  Bready Shop   
332 Hill St      San Francisco     USA         25   3  Super River   
3995 23rd St     San Francisco     USA         10   4   Ben's Shop   
1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
551 Alvarado St  San Francisco     USA         20   6   Richvalley   

                            State  
Address                            
3666 21st St             CA 94114  
735 Dolores St           CA 94119  
332 Hill St      California 94114  
3995 23rd St             CA 94114  
1056 Sanchez St        California  
551 Alvarado St          CA 94114  




                          City Country  Employees  ID         Name       State
Address                                                             

In [43]:
# add new rows and colum or data 
# new colunm
tempJson['Continent'] = tempJson.shape[0] * ['North America']


City Country  Employees  ID         Name  \
Address                                                              
3666 21st St     San Francisco     USA          8   1      Madeira   
735 Dolores St   San Francisco     USA         15   2  Bready Shop   
332 Hill St      San Francisco     USA         25   3  Super River   
3995 23rd St     San Francisco     USA         10   4   Ben's Shop   
1056 Sanchez St  San Francisco     USA         12   5      Sanchez   
551 Alvarado St  San Francisco     USA         20   6   Richvalley   

                            State      Continent  
Address                                           
3666 21st St             CA 94114  North America  
735 Dolores St           CA 94119  North America  
332 Hill St      California 94114  North America  
3995 23rd St             CA 94114  North America  
1056 Sanchez St        California  North America  
551 Alvarado St          CA 94114  North America

In [13]:



## Arithmetic operations

data1=DataFrame({"Speed":[100,103,105]
,"Temp":[34,23,55]
})

data2=DataFrame({"Speed":[111,200,85]
,"Temp":[55,53,5],
"Humidity":[45,55,99]
})
Seris=Series([1,2,3])
Seris1=Series([1,2,3],index=["Speed","Humidity","Temp"])


print(data1+data2)
print(data1**2)
print(data1+2)
print(data1%3)
print(data1**data2)
print(Seris*data1)
print(Seris1*data1)
print(Seris1+data1)
print(Seris1+data2)


   Humidity  Speed  Temp
0       NaN    211    89
1       NaN    303    76
2       NaN    190    60
   Speed  Temp
0  10000  1156
1  10609   529
2  11025  3025
   Speed  Temp
0    102    36
1    105    25
2    107    57
   Speed  Temp
0      1     1
1      1     2
2      0     1
   Humidity                Speed                 Temp
0       NaN                    0  4071254063142928384
1       NaN  1207163699033777601  2688227151811855479
2       NaN  6147008343355840265            503284375
   Speed  Temp   0   1   2
0    NaN   NaN NaN NaN NaN
1    NaN   NaN NaN NaN NaN
2    NaN   NaN NaN NaN NaN
   Humidity  Speed  Temp
0       NaN    100   102
1       NaN    103    69
2       NaN    105   165
   Humidity  Speed  Temp
0       NaN    101    37
1       NaN    104    26
2       NaN    106    58
   Humidity  Speed  Temp
0        47    112    58
1        57    201    56
2       101     86     8


In [14]:

##sorting
print(data1.sort_index())
print(data1.sort_values("Temp"))
print(data1.sort_values(by="Speed"))
print(data1.sort_index(axis=1))


   Speed  Temp
0    100    34
1    103    23
2    105    55
   Speed  Temp
1    103    23
0    100    34
2    105    55
   Speed  Temp
0    100    34
1    103    23
2    105    55
   Speed  Temp
0    100    34
1    103    23
2    105    55


In [15]:

# maj math
print(data1,spacer)
print(data1.sum(axis=1))
print(data2.max())
print(data2.idxmax())


   Speed  Temp
0    100    34
1    103    23
2    105    55 





0    134
1    126
2    160
dtype: int64
Humidity     99
Speed       200
Temp         55
dtype: int64
Humidity    2
Speed       1
Temp        0
dtype: int64


In [16]:


# np.nan droping
data1=DataFrame({"Speed":[100,np.nan,105]
,"Temp":[34,np.nan,55]
})

data2=DataFrame({"Speed":[111,200,85]
,"Temp":[55,53,5],
"Humidity":[45,55,99]
})

print(data1)
print(data1.dropna())

data1=DataFrame({"Speed":[100,np.nan,105]
,"Temp":[34,np.nan,55]
})

print(data1.fillna(100))

   Speed  Temp
0  100.0  34.0
1    NaN   NaN
2  105.0  55.0
   Speed  Temp
0  100.0  34.0
2  105.0  55.0
   Speed   Temp
0  100.0   34.0
1  100.0  100.0
2  105.0   55.0


<h1>Series</h1>

In [17]:
# init
from pandas import Series
se= Series([1,2,3,4,5,6])


In [18]:
print(se,se[0],se[3],)

s2=Series([100,110,120,130],index=[0,1,2,5])
print(s2)
s2=Series([100,110,120,130],index=[0,"a",2,5])
print(s2,s2[0],s2["a"],sep = "\n")


0    1
1    2
2    3
3    4
4    5
5    6
dtype: int64 1 4
0    100
1    110
2    120
5    130
dtype: int64
0    100
a    110
2    120
5    130
dtype: int64
100
110


In [19]:

salaries ={"Albert":81000,"Mat":8000,"Bill":83213000,"Carry":7000}

NewSalaries=Series(salaries)

print(NewSalaries)



Albert       81000
Bill      83213000
Carry         7000
Mat           8000
dtype: int64


In [20]:
S= Series(data=[100,200,300,400,500,600], index=["a","b","c","d","e","f"])
print(S)

S=S.reindex(["f","a","b","c","d","e"])
print(S)


a    100
b    200
c    300
d    400
e    500
f    600
dtype: int64
f    600
a    100
b    200
c    300
d    400
e    500
dtype: int64


In [21]:

sAlpha=Series(data=[1,2,3,4,5,6,7])
sBeta=Series(data=[2,3,4,5,6,7])

print(sAlpha+sAlpha)
print(sBeta+sAlpha)
print(sAlpha*sAlpha)
print(sAlpha**2)
print(sAlpha*2)
print(sAlpha-2)
print(sAlpha%3)

0     2
1     4
2     6
3     8
4    10
5    12
6    14
dtype: int64
0     3.0
1     5.0
2     7.0
3     9.0
4    11.0
5    13.0
6     NaN
dtype: float64
0     1
1     4
2     9
3    16
4    25
5    36
6    49
dtype: int64
0     1
1     4
2     9
3    16
4    25
5    36
6    49
dtype: int64
0     2
1     4
2     6
3     8
4    10
5    12
6    14
dtype: int64
0   -1
1    0
2    1
3    2
4    3
5    4
6    5
dtype: int64
0    1
1    2
2    0
3    1
4    2
5    0
6    1
dtype: int64


In [22]:
##sorting

ser=Series([3,4,59,8,7,55,6,-2],index=[1,5,9,87,6,5,4,2])
print(ser)
print(ser.sort_index())
print(ser.sort_values())

Sap=Series(data=[100,110,100,155,100,55,68],index=["a","b","c","d","d","e","u"])

print(Sap.index.is_unique)
print(Sap.sum())


1      3
5      4
9     59
87     8
6      7
5     55
4      6
2     -2
dtype: int64
1      3
2     -2
4      6
5      4
5     55
6      7
9     59
87     8
dtype: int64
2     -2
1      3
5      4
4      6
6      7
87     8
5     55
9     59
dtype: int64
False
688


In [23]:

## Nan

res=Series(data=[1,2,3,4,5,6,7,np.nan], index=["a","b","c","d","e","f","g","h"])

print(res)
print(res.dropna())

a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    6.0
g    7.0
h    NaN
dtype: float64
a    1.0
b    2.0
c    3.0
d    4.0
e    5.0
f    6.0
g    7.0
dtype: float64


<h1>Panda X Numpy </h1>

In [24]:
mat = dataCSV.as_matrix()
print(mat[0:10,0:10])


[[ 17.93020121  94.52059195 320.2595296 ]
 [ 97.14469719  69.59328198 404.63447153]
 [ 81.77590078   5.7376481  181.48510774]
 [ 55.85434242  70.32590168 321.77363802]
 [ 49.36654999  75.11404016 322.46548558]
 [  3.19270247  29.25629886  94.6188109 ]
 [ 49.20078406  86.14443851 356.34809275]
 [ 21.8828039   46.8415052  181.65376923]
 [ 79.50986272  87.39735554 423.55774319]
 [ 88.1538875   65.20564193 369.22924544]]


In [25]:
# np x[0] -> oth row
# pd x[0] -> col that has the name '0' or the first col
print(dataCSV[0],mat[0])

0     17.930201
1     97.144697
2     81.775901
3     55.854342
4     49.366550
5      3.192702
6     49.200784
7     21.882804
8     79.509863
9     88.153887
10    60.743854
11    67.415582
12    48.318116
13    28.829972
14    43.853743
15    25.313694
16    10.807727
17    98.365746
18    29.146910
19    65.100302
20    24.644113
21    37.559805
22    88.164506
23    13.834621
24    64.410844
25    68.925992
26    39.488442
27    52.463178
28    48.484787
29     8.062088
        ...    
70    30.187692
71    11.788418
72    18.292424
73    96.712668
74    31.012739
75    11.397261
76    17.392556
77    72.182694
78    73.980021
79    94.493058
80    84.562821
81    51.742474
82    53.748590
83    85.050835
84    46.777250
85    49.758434
86    24.119257
87    27.201576
88     7.009596
89    97.646950
90     1.382983
91    22.323530
92    45.045406
93    40.163991
94    53.182740
95    46.456779
96    77.130301
97    68.600608
98    41.693887
99     4.142669
Name: 0, Length: 100, dt

<h1>Functions with pandas /  map / apply</h1>

<p>
# interaction = []</p>
<p>
# for idx, row in df.iterrows():</p>
<p>
#     x1x2 =row['x1'] * row ['x2']</p>
<p>
#     interaction.append(x1x2)</p>
<p>
# df['x1x2'] = interaction
</p>
<p> is same as: df['x1x2']= df.apply(lambda row : row['x1']*row['x2'],axis = 1)</p>

In [26]:

print(dataCSV.head())
dataCSVNew = dataCSV
dataCSVNew[0]= dataCSV.apply(lambda num :num *2 ,axis = 1)
print(dataCSV.head())


           0          1           2
0  17.930201  94.520592  320.259530
1  97.144697  69.593282  404.634472
2  81.775901   5.737648  181.485108
3  55.854342  70.325902  321.773638
4  49.366550  75.114040  322.465486
            0          1           2
0   35.860402  94.520592  320.259530
1  194.289394  69.593282  404.634472
2  163.551802   5.737648  181.485108
3  111.708685  70.325902  321.773638
4   98.733100  75.114040  322.465486


<h1>combine / join / merge</h1>


In [27]:
dft = pd.merge(dataCSVNew,dataCSV,on=0)
print(dft.head(),dataCSVNew.head(),dataCSV.head(),sep="\n\n")


            0        1_x         2_x        1_y         2_y
0   35.860402  94.520592  320.259530  94.520592  320.259530
1  194.289394  69.593282  404.634472  69.593282  404.634472
2  163.551802   5.737648  181.485108   5.737648  181.485108
3  111.708685  70.325902  321.773638  70.325902  321.773638
4   98.733100  75.114040  322.465486  75.114040  322.465486

            0          1           2
0   35.860402  94.520592  320.259530
1  194.289394  69.593282  404.634472
2  163.551802   5.737648  181.485108
3  111.708685  70.325902  321.773638
4   98.733100  75.114040  322.465486

            0          1           2
0   35.860402  94.520592  320.259530
1  194.289394  69.593282  404.634472
2  163.551802   5.737648  181.485108
3  111.708685  70.325902  321.773638
4   98.733100  75.114040  322.465486
